version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - app-network
    volumes:
      - ./.cache/pgdata:/var/lib/postgresql

  pgadmin:
    container_name: ${PGADMIN_CONTAINER_NAME}
    image: dpage/pgadmin4:6.16
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    ports:
      - ${PGADMIN_LISTEN_PORT}:${PGADMIN_LISTEN_PORT}
    volumes:
      - ./.cache/pgadmin:/var/lib/pgadmin
    networks:
      - app-network

  # cache:
  #   container_name: redis_cache
  #   image: redis
  #   restart: always
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - ./.cache:/data
